# Generated by Django 2.2.14 on 2020-08-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0002_remove_cvpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvpost',
            name='contactNumber',
            field=models.CharField(max_length=13),
        ),
    ]
